formatter: "markdown table"
header-from: main.tf
content: |-
  ## DevOps Exercise
  ### Justification
  This module creates a single ec2 web service via Terraform.

  {{ .Providers }}
  
  The following information needs to be provided to the module in order for it to run

  {{ .Inputs }}

  The following information will be provided when terraform completes

  {{ .Outputs }}

output:
  file: "README.md"
  mode: replace
  template: |-
    {{ .Content }}
    {{/** End of file fixer */}}